### ISSUE TITLE
Option to self-host with private PAT

### ISSUE THREAD

**Issue by JamesNZL** [pumbas600/github-contributions#24]
### Related Problem

Private contributions are not currently displayed.

### Requested Feature

Would be neat if there was an option to host our own instance with a PAT to include our private contributions :)

eg see https://github.com/anuraghazra/github-readme-stats/issues/2500#issuecomment-1420570545

**Comment by pumbas600** [comment]
Huh, this is interesting. Private contributions seem to be included for me (Although, that might be because it's using my PAT).

Can I check if have you enabled private contributions in your contribution settings? From a brief glance, it looks like your graph matches with GitHub's contribution chart.

![image](https://github.com/pumbas600/github-contributions/assets/38820160/6bb7e6a6-cc7e-4f80-b75c-ce50aae106ae)

**Comment by JamesNZL** [comment]
Hmm... you're right 😅 

The graph is lining up with the chart, including private contribs.

Can't remember the specifics (and am too tired to dig at the moment), but none of my private contribs would show up before I self-hosted my own instance of https://github.com/anuraghazra/github-readme-stats... but it is very likely that these are different APIs (ie counting PRs in private repos, vs just taking the number of private contribs on a day)... oops

I guess that is what I get for creating an issue in the middle of a lecture :grinning:

**Comment by pumbas600** [comment]
Haha, it's all good. I'm glad it seems to working though ❤️
